// Generated by gencpp from file grid_path_searcher/get_plan.msg
// DO NOT EDIT!


#ifndef GRID_PATH_SEARCHER_MESSAGE_GET_PLAN_H
#define GRID_PATH_SEARCHER_MESSAGE_GET_PLAN_H

#include <ros/service_traits.h>


#include <grid_path_searcher/get_planRequest.h>
#include <grid_path_searcher/get_planResponse.h>


namespace grid_path_searcher
{

struct get_plan
{

typedef get_planRequest Request;
typedef get_planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_plan
} // namespace grid_path_searcher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_path_searcher::get_plan > {
  static const char* value()
  {
    return "647c71abdcf22e8d9ecf2dcc45d55169";
  }

  static const char* value(const ::grid_path_searcher::get_plan&) { return value(); }
};

template<>
struct DataType< ::grid_path_searcher::get_plan > {
  static const char* value()
  {
    return "grid_path_searcher/get_plan";
  }

  static const char* value(const ::grid_path_searcher::get_plan&) { return value(); }
};


// service_traits::MD5Sum< ::grid_path_searcher::get_planRequest> should match 
// service_traits::MD5Sum< ::grid_path_searcher::get_plan > 
template<>
struct MD5Sum< ::grid_path_searcher::get_planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::get_plan >::value();
  }
  static const char* value(const ::grid_path_searcher::get_planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::get_planRequest> should match 
// service_traits::DataType< ::grid_path_searcher::get_plan > 
template<>
struct DataType< ::grid_path_searcher::get_planRequest>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::get_plan >::value();
  }
  static const char* value(const ::grid_path_searcher::get_planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_path_searcher::get_planResponse> should match 
// service_traits::MD5Sum< ::grid_path_searcher::get_plan > 
template<>
struct MD5Sum< ::grid_path_searcher::get_planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::get_plan >::value();
  }
  static const char* value(const ::grid_path_searcher::get_planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::get_planResponse> should match 
// service_traits::DataType< ::grid_path_searcher::get_plan > 
template<>
struct DataType< ::grid_path_searcher::get_planResponse>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::get_plan >::value();
  }
  static const char* value(const ::grid_path_searcher::get_planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_PATH_SEARCHER_MESSAGE_GET_PLAN_H
