// Generated by gencpp from file grid_path_searcher/test.msg
// DO NOT EDIT!


#ifndef GRID_PATH_SEARCHER_MESSAGE_TEST_H
#define GRID_PATH_SEARCHER_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <grid_path_searcher/testRequest.h>
#include <grid_path_searcher/testResponse.h>


namespace grid_path_searcher
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace grid_path_searcher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_path_searcher::test > {
  static const char* value()
  {
    return "647c71abdcf22e8d9ecf2dcc45d55169";
  }

  static const char* value(const ::grid_path_searcher::test&) { return value(); }
};

template<>
struct DataType< ::grid_path_searcher::test > {
  static const char* value()
  {
    return "grid_path_searcher/test";
  }

  static const char* value(const ::grid_path_searcher::test&) { return value(); }
};


// service_traits::MD5Sum< ::grid_path_searcher::testRequest> should match 
// service_traits::MD5Sum< ::grid_path_searcher::test > 
template<>
struct MD5Sum< ::grid_path_searcher::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::test >::value();
  }
  static const char* value(const ::grid_path_searcher::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::testRequest> should match 
// service_traits::DataType< ::grid_path_searcher::test > 
template<>
struct DataType< ::grid_path_searcher::testRequest>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::test >::value();
  }
  static const char* value(const ::grid_path_searcher::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_path_searcher::testResponse> should match 
// service_traits::MD5Sum< ::grid_path_searcher::test > 
template<>
struct MD5Sum< ::grid_path_searcher::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::test >::value();
  }
  static const char* value(const ::grid_path_searcher::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::testResponse> should match 
// service_traits::DataType< ::grid_path_searcher::test > 
template<>
struct DataType< ::grid_path_searcher::testResponse>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::test >::value();
  }
  static const char* value(const ::grid_path_searcher::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_PATH_SEARCHER_MESSAGE_TEST_H
