// Generated by gencpp from file grid_path_searcher/update_goal.msg
// DO NOT EDIT!


#ifndef GRID_PATH_SEARCHER_MESSAGE_UPDATE_GOAL_H
#define GRID_PATH_SEARCHER_MESSAGE_UPDATE_GOAL_H

#include <ros/service_traits.h>


#include <grid_path_searcher/update_goalRequest.h>
#include <grid_path_searcher/update_goalResponse.h>


namespace grid_path_searcher
{

struct update_goal
{

typedef update_goalRequest Request;
typedef update_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct update_goal
} // namespace grid_path_searcher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grid_path_searcher::update_goal > {
  static const char* value()
  {
    return "647c71abdcf22e8d9ecf2dcc45d55169";
  }

  static const char* value(const ::grid_path_searcher::update_goal&) { return value(); }
};

template<>
struct DataType< ::grid_path_searcher::update_goal > {
  static const char* value()
  {
    return "grid_path_searcher/update_goal";
  }

  static const char* value(const ::grid_path_searcher::update_goal&) { return value(); }
};


// service_traits::MD5Sum< ::grid_path_searcher::update_goalRequest> should match 
// service_traits::MD5Sum< ::grid_path_searcher::update_goal > 
template<>
struct MD5Sum< ::grid_path_searcher::update_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::update_goal >::value();
  }
  static const char* value(const ::grid_path_searcher::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::update_goalRequest> should match 
// service_traits::DataType< ::grid_path_searcher::update_goal > 
template<>
struct DataType< ::grid_path_searcher::update_goalRequest>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::update_goal >::value();
  }
  static const char* value(const ::grid_path_searcher::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grid_path_searcher::update_goalResponse> should match 
// service_traits::MD5Sum< ::grid_path_searcher::update_goal > 
template<>
struct MD5Sum< ::grid_path_searcher::update_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grid_path_searcher::update_goal >::value();
  }
  static const char* value(const ::grid_path_searcher::update_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grid_path_searcher::update_goalResponse> should match 
// service_traits::DataType< ::grid_path_searcher::update_goal > 
template<>
struct DataType< ::grid_path_searcher::update_goalResponse>
{
  static const char* value()
  {
    return DataType< ::grid_path_searcher::update_goal >::value();
  }
  static const char* value(const ::grid_path_searcher::update_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRID_PATH_SEARCHER_MESSAGE_UPDATE_GOAL_H
